name: Test django-altcha-middleware

on: [push, pull_request, workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ['3.9', '3.10', '3.11', '3.12']
        django: ['4.2', '5.0', '5.1', '5.2']

    steps:
      - uses: actions/checkout@v4
      - name: Setup Python ${{ matrix.python }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install django~=${{ matrix.django }}
          pip install -r requirements.txt -r requirements-test.txt
      - name: Run the tests (and collect coverage data)
        run: coverage run -m pytest
      - name: Lint with flake8
        if: ${{ matrix.python == '3.12' }} && ${{ matrix.django == '4.2' }}
        run: flake8 dam tests --count --max-line-length=99 --statistics
      - name: Show the test coverage report
        if: ${{ matrix.python == '3.12' }} && ${{ matrix.django == '4.2' }}
        run: coverage report -m --fail-under=95
